### ISSUE TITLE
6-pin header connections (JP4)

### ISSUE THREAD

**Issue by daescalona** [sparkfun/XBee_Explorer_Regulated#1]
Hello,

I have been playing recently with Sparkfun boards and XBee devices, specifically I have used these two boards:
- SparkFun XBee Explorer Regulated Board: https://www.sparkfun.com/products/11373
- SparkFun FTDI Basic Breakout - 3.3V: https://www.sparkfun.com/products/9873

So, the first thought I had as a customer is that the 6-pin header connector of each board was compatible, and I could attach one board to the other one using a 90º pin header connector. I was wrong, only GND and VCC lines are compatible. The Rx and Tx lines are crossed, which is the main issue, but also the DTR and CTS lines are wrong. So I have several questions:
- Is there any reason the 6 pin header (JP4) is designed that way? (maybe compatibility with any other board or something?) Could it be updated/improved so that it is 1:1 compatible with the FTDI boards?
- Could Rx and Tx lines be interchanged in the JP4 header connector?
- Why is CTS line of JP4 connected to ground? It should be connected to pin 12 of XBee (JP3 9).
- Why is DTR line of JP4 connected to XBee DIO3 (JP3 4)? That line should be connected to pin 9 of XBee (JP2 2).

The DTR and CTS lines issue is specially worrying. It avoids users to use Hardware Flow control in the connected XBee device as the lines are no properly connected to the XBee socket.

I am attaching an image displaying what must be done currently to attach both boards:

![rx_tx_lines_cross](https://cloud.githubusercontent.com/assets/8180010/17594190/b3d91d2a-5fe8-11e6-9c7e-2a08217c20fe.jpg)

Kind regards.

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I noticed your question when browsing a few issues. If you are still wondering, the serial interface (JP4) on the XBee Explorer was designed to directly mate with Arduino development boards. It was not designed to mate directly with an FTDI  since the board was intended to be the "FTDI-side" of the standard "Arduino <=> FTDI" setup. The CTS and DTR pins were arranged in this fashion for simple serial interface and [wireless bootloading](https://www.sparkfun.com/tutorials/122). 

As a result, there are no plans to update the board to be 1:1 compatible with an FTDI.
